# Generated by Django 5.0.3 on 2024-03-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'available'), (1, 'running low'), (2, 'out of stock')], default=2)),
            ],
        ),
    ]
